C %P%

      SUBROUTINE RGPS2 (IVEC, NVEC, NR, NC, N4, LENG, G, B, IAUX, IVF,
     &     SIGUWT, A, NX, IGRT, KINDS,ISNS,JSNS,LOBS)
********************************************************************************
* COMPUTE RESIDUALS IN X,Y,Z AND E,N,U. FOR A GPS VECTOR
*   PUT V-TILDE H IN COLUMN N2+1 OF G
*   PUT V-TILDE U IN COLUMN N2+2 OF G
********************************************************************************

* * * MODIFIED 1/2/91 TO PRINT ALL RESIDUALS REGARLESS OF THE SIZE

      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      IMPLICIT INTEGER (I-N)
      PARAMETER ( NVECS = 700, MXSSN = 9999 )

**v 4.28
      PARAMETER ( MAXC = 9999 )

      DIMENSION ICM((NVECS+1)*3+1+3)
      DIMENSION KINDS(NVECS*3), ISNS(NVECS*3), JSNS(NVECS*3)
      DIMENSION LOBS(NVECS*3)
      LOGICAL LBB, LGF, LCS, LVD, LVA, LVZ, LVS, LVR, LVG,
     &        LVC, LIS, LPS, LPG, LDR, LOS, LAP, LDF, LVX, LGV
      LOGICAL FATAL, NOBIGV
      LOGICAL LSS, LUP, LMSL, LABS, LADJ, LUPI
      LOGICAL L2HLF, LEHT
      LOGICAL LNEWX
***************
      DIMENSION G(NR,NC), B(*), A(*), NX(*)
      COMMON /GRTTB1/ GLAT0, GLON0, R0(3,3)
      COMMON /DUAL/   N2HLF, I2HLF(MXSSN), L2HLF, LEHT
      COMMON/UNITS/ LUNIT
      CHARACTER*99 SCCSID

C      SCCSID='$Id: rgps2.for 44197 2010-07-13 12:26:03Z bruce.tran $	20$Date: 2008/08/25 16:03:07 $ NGS'

C   CONVERT RESIDUALS TO E,N,U.
*******    PUT V-TILDE H IN COLUMN 1 OF GPSVS
*******    PUT V-TILDE U IN COLUMN 2 OF GPSVS
      I=3*(IVEC-1)+1
      ISN = ISNS(I)
      JSN = JSNS(I)

*** GET COVARIANCE MATRIX

      NVEC = NR/3
      CALL GLOCAT(N1,N2,N3,N4,N5,NVEC,LENG)

C   GET XYZ RESIDUALS FROM COLUMN N4
      VX = G(3*(IVEC-1)+1,N4)
      VY = G(3*(IVEC-1)+2,N4)
      VZ = G(3*(IVEC-1)+3,N4)

      CALL TOLGH2 (VX,VY,VZ,VN,VE,VU,ISN, JSN, B, G, IVEC,NR,NC)
C
C      WRITE(LUNIT,6501) IOBS,VX,VY,VZ,VN,VE,VU
 6501 FORMAT(I8, 6F12.4)

      RETURN
      END
